sudo: false
language: node_js
node_js:
  - node
  - '6'
before_install:
- echo arangodb3 arangodb/password password root | sudo debconf-set-selections  # set username 'root'
- echo arangodb3 arangodb/password_again password root | sudo debconf-set-selections  # set password 'root'
- curl -s -L https://raw.githubusercontent.com/brennv/arangodb-travis/master/setup_arangodb.sh -o setup_arangodb.sh
- chmod +x setup_arangodb.sh
- ./setup_arangodb.sh
script:
  - yarn run test
after_script:
  - kill -9 $(pgrep arangod)
cache:
  yarn: true
  directories:
    - node_modules
