sudo: required
language: node_js
node_js:
  - node
  - '8'
services:
  - docker
before_install:
- docker pull arangodb
- docker run -e ARANGO_ROOT_PASSWORD=root -p 8529:8529 -d arangodb
script:
  - yarn run test
after_script:
  - kill -9 $(pgrep arangod)
cache:
  yarn: true
  directories:
    - node_modules
